// omg we do have a includes i didnt see this lmfao
#pragma once

#include "vars.h"
#include "Renderer/renderer.hpp"
#include "paths.h"
#include <Geode/Geode.hpp>
#include <Geode/modify/CCKeyboardDispatcher.hpp>
#include <Geode/modify/GJGameLevel.hpp>
#include <imgui-cocos.hpp>
#include <Geode/modify/MenuLayer.hpp>
#include <Geode/modify/GJBaseGameLayer.hpp>
#include <cmath>
#include <Geode/modify/PlayLayer.hpp>
#include <Geode/modify/PlayerObject.hpp>
#include <Geode/modify/CCDelayTime.hpp>
#include <vector>
#include <string>
#include <cstring>
#include <algorithm>
#include "GUI/gui.hpp"
#include <Geode/modify/CCScheduler.hpp>
#include "GUI/mobile/mobileUI.hpp"
#include <Geode/modify/CCDirector.hpp>
#include <Geode/modify/ShaderLayer.hpp>
#include <Geode/modify/EditLevelLayer.hpp>
#include <Geode/modify/LevelInfoLayer.hpp>
#include <Geode/modify/UILayer.hpp>
#include <Geode/modify/GameLevelManager.hpp>
#include <Geode/modify/GameStatsManager.hpp>
#include <Geode/modify/GameManager.hpp>
#include <Geode/modify/GameToolbox.hpp>
#include <Geode/modify/GhostTrailEffect.hpp>
#include <Geode/modify/RingObject.hpp>
#include <filesystem>
#include "Logic/Logger/logger.hpp"
#include "Logic/Keybinds/keybinds.hpp"
#include "Logic/Hacks/QOL/qol.hpp"
#include "Logic/Hacks/Cosmetics/cosmetics.hpp"
#include "Logic/Hacks/Bottinghacks/hacks.hpp"
#include "Logic/Hacks/Bottinghacks/PracticeFix.hpp"
#include <Geode/utils/file.hpp> // geode::Result<>watchFile(std::filesystem::pathconst&file)
#include <Geode/modify/CCSprite.hpp>
#include <Geode/modify/CCSpriteFrameCache.hpp>
#include <Geode/modify/CCTextureCache.hpp>
#include <Geode/modify/CCLabelBMFont.hpp>
#include <Geode/modify/CCMenuItemSprite.hpp>
#include <Geode/modify/CCMenuItemToggler.hpp>
#include <Geode/modify/CCMenuItemSpriteExtra.hpp>
#include <Geode/modify/CCMenu.hpp>
#include <Geode/modify/CCLayerColor.hpp>
#include <Geode/modify/CCTextInputNode.hpp>
#include <Geode/modify/CCDirector.hpp>
#include <Geode/modify/CCMenuItemSpriteExtra.hpp>
#include <Geode/modify/CCMenuItemToggler.hpp>
#include <Geode/modify/CCMenu.hpp>
#include <Geode/modify/CCLayerColor.hpp>
#include <Geode/modify/CCTextInputNode.hpp>
#include <Geode/modify/CCSprite.hpp>
#include <Geode/modify/CCSpriteFrameCache.hpp>
#include <Geode/modify/CCTextureCache.hpp>
#include <Geode/modify/CCLabelBMFont.hpp>
#include <Geode/modify/CCDirector.hpp>
#include "Logic/Bot/framecount.hpp"
#include "Logic/Bot/bot.hpp"
#include "builds/assembler.hpp"
#include <Geode/modify/EffectGameObject.hpp>
#include <Geode/modify/EnhancedGameObject.hpp>
#include <Geode/modify/GameObject.hpp>
#include <Geode/modify/HardStreak.hpp>
#include <Geode/modify/LevelEditorLayer.hpp>
#include <Geode/modify/CCDrawNode.hpp>
#include <Geode/modify/EditorUI.hpp>
#include "HackData.hpp"
#include "Logic/Hacks/Labels/Label.hpp"